openapi: 3.0.0

info:
  title: RP Flask REST API
  description: An API about people and notes
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
        timestamp:
          type: "string"
  parameters:
    lname:
      name: lname
      description: "Last name of the person to get from the list"
      in: path
      required: true
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Person"
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person and add it to the people list"
      requestBody:
          description: "Person to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person in list"

  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person from the people list"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: Successfully read person from people list operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person in the people list"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated person in people list"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: person
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person from the people list"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfully deleted person from people list"